Add brunodo handler
Calindra/nonodo pull request #111
Opened 2024-07-09 21:20 UTC by sandhilt

2024-07-10 18:27 UTC, fabiooshiro requested changes
@sandhilt you need to modify the build. Cuz the build changes the package.json to point to the binary.

2024-07-10 20:28 UTC, sandhilt commented
> @sandhilt you need to modify the build. Cuz the build changes the package.json to point to the binary.

Sorry, I don't understand this because don't have process of build.
The change is in `bin` field:

https://github.com/Calindra/nonodo/blob/369d0370261bbd85f86f291eb5878e8bf208589c/npm-package/package.json#L16-L19

Please enlighten me about this issue.

2024-07-11 13:20 UTC, fabiooshiro commented
@sandhilt 
<img width="887" alt="image" src="https://github.com/Calindra/nonodo/assets/218768/f498bb28-b8e6-489f-be34-782725a48de7">

2024-07-11 23:26 UTC, sandhilt commented
> @sandhilt <img alt="image" width="887" src="https://private-user-images.githubusercontent.com/218768/347832678-f498bb28-b8e6-489f-be34-782725a48de7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NDA1NzMsIm5iZiI6MTcyMDc0MDI3MywicGF0aCI6Ii8yMTg3NjgvMzQ3ODMyNjc4LWY0OThiYjI4LWI4ZTYtNDg5Zi1iZTM0LTc4MjcyNWE0OGRlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMVQyMzI0MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MjcyYmFmNGZmMGQ0OWVjMDY5ODBmOTkyM2ExM2VlOWVmMTI2ZGIyYzQyOWY3NjUzNDg0MGVhZjRjNGRmNWU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mKB-Jv12FnZCmIkv5zD-BAA1RqtFlQdhFyofSJI9lZk">

# Proposal changes:
- Change nonodo v1 for nonodo@^1
- Change nonodo v2 from brunodo for nonodo@^2 and keep tracking

Files for keep consistent:
- build process: https://github.com/Calindra/nonodo/blob/369d0370261bbd85f86f291eb5878e8bf208589c/.github/workflows/ci.yaml#L190-L199
- package.json:
	- name: https://github.com/Calindra/nonodo/blob/369d0370261bbd85f86f291eb5878e8bf208589c/npm-package/package.json#L2
	- bin names: https://github.com/Calindra/nonodo/blob/369d0370261bbd85f86f291eb5878e8bf208589c/npm-package/package.json#L17-L18
	- oclif usage name: https://github.com/Calindra/nonodo/blob/369d0370261bbd85f86f291eb5878e8bf208589c/npm-package/.oclifrc.json#L2

2024-07-11 23:27 UTC, sandhilt commented
@fabiooshiro I generate a comment for further investigation or enhancement.

2025-04-04 04:14 UTC, closed without merging